services:
  db:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-postgres:1.0
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-redis:1.0
    ports: 
      - 6379:6379

  web:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-web:1.3

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    user: "1000:1000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    # env_file:
    #   - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5432/fakebook_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  sidekiq:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-sidekiq:1.3
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5432/fakebook_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

volumes:
  dbdata: