# This docker compose not only serves the following services/apps:
# - waldo-react
# - waldo-rails
# - db (postgres container serving all rails services (waldo, fakebook, flight-booker))
# - redis (redis container serving fakebook & flight-booker)
# - nginx (routes all of these services)
# - faekbook (named 'web')
# - sidekiq - (serves fakebook)
# - flight-booker

services:

  portfolio-react:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/portfolio-react:1.1
    expose:
      - 80

  waldo-react:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/waldo-react:1.2
    ports:
      - "3001:80"
    depends_on:
      - waldo-rails

  waldo-rails:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/waldo-rails:1.6
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    user: "1000:1000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${WALDO_RAILS_PRODUCTION_KEY}
      DATABASE_URL: postgresql://${WALDO_DATABASE_USER}:${WALDO_DATABASE_PASSWORD}@db:5432/waldo_production
    env_file:
      - .env

  db:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-postgres:1.0
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-redis:1.0
    ports: 
      - 6379:6379

  nginx:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-nginx:1.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
# Cloudflare universal SSL cert for non www urls binding
      - /etc/nginx/ssl/default.crt:/etc/nginx/ssl/default.crt:ro
      - /etc/nginx/ssl/default.key:/etc/nginx/ssl/default.key:ro
# LetsEncrypt SSL cert for unproxied www.* domains 
      - /etc/nginx/ssl/www/fullchain.pem:/etc/nginx/ssl/www/fullchain.pem:ro
      - /etc/nginx/ssl/www/privkey.pem:/etc/nginx/ssl/www/privkey.pem:ro
# Static HTML page site bindings 
      - ./ubuntu-deploy-site/:/var/www/ubuntu-deploy-site/
    depends_on:
      - web
      - flight-booker

  web:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-web:2.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    user: "1000:1000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://${FAKEBOOK_DATABASE_USER}:${FAKEBOOK_DATABASE_PASSWORD}@db:5432/fakebook_production
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: ${FAKEBOOK_RAILS_PRODUCTION_KEY}
    env_file:
      - .env

# Image below is a replica of the fakebook main rails app image, but this could use a custom dockerfile to build a slimmer image
# by removing; assets, puma web server, some views (not mailers).
  sidekiq:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/fakebook-sidekiq:1.1
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://${FAKEBOOK_DATABASE_USER}:${FAKEBOOK_DATABASE_PASSWORD}@db:5432/fakebook_production
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: ${FAKEBOOK_RAILS_PRODUCTION_KEY} # This is the secret key base for the fakebook app, should be namespaced to fakebook
    env_file:
      - .env
  
  flight-booker:
    image: 964236740875.dkr.ecr.eu-west-3.amazonaws.com/flight-booker:1.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' & bundle exec sidekiq"
    user: "1000:1000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://${FLIGHT_BOOKER_DATABASE_USER}:${FLIGHT_BOOKER_DATABASE_PASSWORD}@db:5432/flight_booker_production
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${FLIGHT_BOOKER_RAILS_PRODUCTION_KEY}
    env_file:
      - .env

volumes:
  dbdata: