services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      # POSTGRES_DB: fakebook_production
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports: 
      - 6379:6379

  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    user: "1000:1000"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    # env_file:
    #   - .env
    environment:
      # RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/fakebook_development
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY_DEVELOPMENT}

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/fakebook_development
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY_DEVELOPMENT}
      RAILS_ENV: development

volumes:
  dbdata: